CREATE DATABASE PETSHOPDB;
use PETSHOPDB;

CREATE TABLE INTERESSADO(
    id INT PRIMARY KEY AUTO_INCREMENT,
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR(80) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE FILHOTE(
    id INT PRIMARY KEY AUTO_INCREMENT,
    especie VARCHAR(255) NOT NULL,
    raca VARCHAR(80) NOT NULL,
    cpf_interesado VARCHAR(11),
    CONSTRAINT fk_interessado FOREIGN KEY (cpf_interesado) REFERENCES INTERESSADO(cpf)
);
